# Generated by Django 6.0.2 on 2026-03-08 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=240)),
                ('package_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchase_unity', models.CharField(choices=[('GRAM', 'Gram'), ('UNITY', 'Unity'), ('KILOGRAM', 'Kilograma')], default='GRAM')),
                ('purchase_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('barcode', models.CharField(max_length=120, unique=True)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=8)),
                ('margin_seller', models.DecimalField(decimal_places=3, default=None, max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
